### ISSUE TITLE
We need a argument :key for construct of TouchableOpacity.

### ISSUE THREAD

**Issue by leeewh** [nkshah2/touchable_opacity#1]
like this : 
TouchableOpacity(
  key:Key("1123"),
  ...
);

**Comment by leeewh** [comment]
thank u!

**Comment by nkshah2** [comment]
Hi, thank you for using this package. You are right, having a way to assign a key is quite fundamental and should have been there since the start. Just out of curiosity what issue did you run into to need this?

If it is something people can run into often I will make a note of this in the README.

**Comment by nkshah2** [comment]
The change has been release in 1.1.0, please feel free to let us know if you face any issues
