### ISSUE TITLE
Hot reloading not working for child of TouchableOpacity

### ISSUE THREAD

**Issue by iksent** [nkshah2/touchable_opacity#2]
Using TouchableOpacity disables hot reloading for children tree.

```
body: TouchableOpacity(child: Text('Test'))
```

Try to change "Test" text to another, hot reloading will be triggered, but nothing changes at the screen of application.
So it's really annoyed to restart the app every time.

BTW everything else is perfect.

**Comment by nkshah2** [comment]
Hi thank you for reporting this issue, can you tell us what version of the package are you using.

**Comment by iksent** [comment]
Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082])

touchable_opacity: ^1.1.0

**Comment by nkshah2** [comment]
@iksent The issue has been fixed and version 1.1.2 has been pushed (It may take some time for pub.dev to finish processing it). Please try on that version and see if the issue still persists.

**Comment by iksent** [comment]
Works perfectly now, thank you!
